export * from "./Login";
export * from "./Register";
export * from "./Dashboard";
export * from "./SinglePost";
export * from "./EditPost";
export * from "./AddPost";
export * from "./MyPosts";
export * from "./Landing";
export * from "./Team";
